[package]
name = "git-diff-stat"
version = "0.1.0"
authors = ["Christoph Rüßler <christoph.ruessler@mailbox.org>"]

[dependencies]
clap = "2"
csv = "1.0.0-beta.5"
git2 = "^0.6"
serde = "1"
serde_derive = "1"
